<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
	<UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Copyright>© 2026 pahipy</Copyright>
    <Company>pahipy</Company>
    <Version>1.4.0.0</Version>
    <ProductName>SText</ProductName>
    <AssemblyName>SText</AssemblyName>
	<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Platforms>x64</Platforms>
	<PublishReadyToRun>true</PublishReadyToRun>
    <ApplicationIcon>Media\STextIcon_Big2.1.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>10.0.18362.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Media\STextIcon_Big2.1.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="FluentIcons.WPF" Version="2.1.337" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.11" />
    <PackageReference Include="UDE.CSharp" Version="1.1.0" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <CustomToolNamespace>SText</CustomToolNamespace>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>